### ISSUE TITLE
Cannot read property 'broccoliNode' of undefined on removed file

### ISSUE THREAD

**Issue by lifeart** [ember-cli/broccoli-middleware#45]
```
TypeError: Cannot read property 'broccoliNode' of undefined
    at errorHandler (C:\waiting-list\src\frontend\node_modules\broccoli-middleware\lib\utils\error-handler.js:17:40)
    at watcher.then (C:\waiting-list\src\frontend\node_modules\broccoli-middleware\lib\watcher-middleware.js:37:7)
    at tryCatcher (C:\waiting-list\src\frontend\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:329:19)
    at invokeCallback (C:\waiting-list\src\frontend\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:507:31)
    at C:\waiting-list\src\frontend\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:571:14
    at flush (C:\waiting-list\src\frontend\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:2432:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by stefanpenner** [comment]
fixed as of v2.1.1
